# Generated by Django 5.2.15 on 2026-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guessStatistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guessattempt",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
