# Generated by Django 5.2.15 on 2026-06-11 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guessStatistics", "0002_alter_guessattempt_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guessattempt", options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="guessattempt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
