# Generated by Django 5.2.15 on 2026-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guessStatistics", "0003_alter_guessattempt_options_guessattempt_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guessattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
